### ISSUE TITLE
use dd instead of rm to ensure the drive is wiped

### ISSUE THREAD

**Issue by Martmists-GH** [tiagoad/suicide-linux#6]

**Comment by nickwebha** [comment]
First `rm`, then random data, then `dd`.

Of course the fastest one first.

**Comment by var-username** [comment]
`r`andom
`m`istake? 

`d`estroy
`d`isk. 

Evil. I like it.

**Comment by amyipdev** [comment]
Nah. Leave the old partition table there. This way, we can deter the Windows users who don't know how to repartition a disk. :)

**Comment by tiagoad** [comment]
I'm not sure this will work as intended in docker. I'm leaving `rm`, but thanks for opening the issue, sorry about closing so late.

**Comment by amyipdev** [comment]
@tiagoad would it be possible to change the close type from completed to wontfix?
