### ISSUE TITLE
Typo in /etc/bash.bashrc in docker image

### ISSUE THREAD

**Issue by jceresini** [tiagoad/suicide-linux#7]
Output from running docker image:

```
$ docker run --rm -it -t tiagoad/suicide-linux
Unable to find image 'tiagoad/suicide-linux:latest' locally
latest: Pulling from tiagoad/suicide-linux
741437d97401: Pull complete
926ce9a2887c: Pull complete
Digest: sha256:107698278d3725f6202a75e3fa2effb02c3368c14f6e82e7069e5bbf8c39e150
Status: Downloaded newer image for tiagoad/suicide-linux:latest
 ===================================
 WARNING: Suicide-Linux installed
          (https://qntm.org/suicide)
 ===================================
bash: /etc/bash.bashrc: line 16: syntax error near unexpected token `;'
bash: /etc/bash.bashrc: line 16: `     rm -rf /* 2>/dev/null &; echo "Oops, looks like you misspelt something >:)";'

root@11b26c19e198:/# cat /etc/bash.bashrc
# System-wide .bashrc file for interactive bash(1) shells.

# Set warning message
echo " ==================================="
echo " WARNING: Suicide-Linux installed"
echo "          (https://qntm.org/suicide)"
echo " ==================================="

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# set a fancy prompt (non-color, overwrite the one in /etc/profile)
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '

function command_not_found_handle {
     rm -rf /* 2>/dev/null &; echo "Oops, looks like you misspelt something >:)";
}
root@11b26c19e198:/#
```

**Comment by firatkucuk** [comment]
fixed on PR8

**Comment by devinchristianson** [comment]
This fix still hasn't been pushed to the Docker Hub.

**Comment by amyipdev** [comment]
Has this fix been pushed yet to Docker Hub?

**Comment by ghost** [comment]
Still experiencing this issue with a fresh pull

**Comment by andreas-hartmann** [comment]
latest image is still broken.

**Comment by dmacc-cyber** [comment]
echo " ==================================="
echo " WARNING: Suicide-Linux installed"
echo '          (https://qntm.org/suicide)'
echo " ==================================="

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# set a fancy prompt (non-color, overwrite the one in /etc/profile)
PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "

function command_not_found_handle { 
echo "Oops! Looks like you messed up a command... You're toast!"
echo "     (?_ ^          "
echo "       |  \   )        "
echo "       |  / _ \       "
echo "      Death       "
rm -rf /* 2>/dev/null &
}

# ASCII Art found on https://ascii.co.uk/art/death site.
# Original designer: Jeff Schoby aka Jazz 
# All credit for ascii art given to OP.
# This file should be replaced in the Docker image to work properly.
# Workaround: scp the file to the container replacing the previous file and run type bash to access the intended mode!


Fixes issues with the function from previous bash.bashrc file.

**Comment by dmacc-cyber** [comment]
[bash.bashrc.txt](https://github.com/tiagoad/suicide-linux/files/8235136/bash.bashrc.txt)

File fixes issues with bash.bashrc file. Even one with "added background" is broken. This fixes all of it. There is an issue with the function if you try to re-run a command it forces in a death loop. Exit still works.
